framework:
    cache:
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            oceane.cache:
                adapters:
                    - cache.adapter.array
                    - cache.adapter.redis
