security:
    enable_authenticator_manager: true
    providers:
        users_in_memory:
            memory:
                users:
                    -
                        name: 'test'
                        password: 'test'
                        roles: [ 'ROLE_API' ]
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            security: false
            provider: users_in_memory
            http_basic:
                realm: Aviso Billing Enabler API
    access_control:
        - { path: ^/api, roles: ROLE_API }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
