name: php-cs-fixer
on: [push, pull_request]
jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: apcu, ctype, iconv, intl, json, mbstring, pdo
            - run: cd tools/php-cs-fixer/ && composer i && cd -
            - run: ./tools/php-cs-fixer/run.sh
