name: phpstan
on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]
jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extensions: apcu, ctype, iconv, intl, json, mbstring, pdo
            - uses: ramsey/composer-install@v1
              with:
                  composer-options: -n -o --no-scripts
            - run: ./bin/console cache:clear
            - run: ./tools/phpstan/run.sh
